### ISSUE TITLE
Use BM3DCUDA

### ISSUE THREAD

**Issue by Ryuukishi** [IFeelBloated/Oyster#6]
Now that there is a native Vapoursynth plugin for [CUDA accelerated BM3D](https://github.com/WolframRhodium/VapourSynth-BM3DCUDA), can we get this integrated into Oyster/Plum/Vine to speed things up?

**Comment by IFeelBloated** [comment]
you could definitely try but I don't have time for this currently, I've got a lot of things going on lately :(

**Comment by MonoS** [comment]
Hi @Ryuukishi, probably you can use the CUDA version changing line 21 and 22 with ```self.core.{bm3d...}.BM3D```
The main problem i can see, not having created this script, is regarding the sigma value as, as stated in the BM3DCUDA version,
>The strength is similar (but not strictly equal) as VapourSynth-BM3D due to differences in implementation. (coefficient normalization is not implemented, for example)

also the CUDA version does not implement a proper Basic estimation.
Both of this facts may change the frequency analysis and hinder the proper working of this script, so without proper knowledge of the inner workings on those script i'd advise against the use of the CUDA version.
